### ISSUE TITLE
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY 

### ISSUE THREAD

**Issue by BRLOKESH** [mrgoonie/flutter_recaptcha_v2#3]
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: RenderConstrainedBox object was given an infinite size during layout.
flutter: This probably means that it is a render object that tries to be as big as possible, but it was put
flutter: inside another render object that allows its children to pick their own size.
flutter: The nearest ancestor providing an unbounded height constraint is:
flutter:   RenderFlex#f541e NEEDS-LAYOUT NEEDS-PAINT
flutter:   creator: Column ← DecoratedBox ← ConstrainedBox ← Container ← Center ← DecoratedBox ← Container ←
flutter:   ConstrainedBox ← Container ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout
flutter:   ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(w=350.0, h=380.0)
flutter:   size: Size(350.0, 380.0)
flutter:   direction: vertical
flutter:   mainAxisAlignment: start
flutter:   mainAxisSize: max
flutter:   crossAxisAlignment: center
flutter:   verticalDirection: down
flutter: The constraints that applied to the RenderConstrainedBox were:
flutter:   BoxConstraints(0.0<=w<=350.0, 0.0<=h<=Infinity)
flutter: The exact size it was given was:
flutter:   Size(350.0, Infinity)
flutter: See https://flutter.dev/layout/ for more information.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1749:9)
flutter: #1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1823:6)
flutter: #2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1543:17)
flutter: #3      RenderBox.size= (package:flutter/src/rendering/box.dart:1543:65)
flutter: #4      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:262:7)
flutter: #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #6      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #8      RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
flutter: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #10     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:737:15)
flutter: #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #12     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:737:15)
flutter: #13     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
flutter: #14     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
flutter: #24     _invoke (dart:ui/hooks.dart:219:10)
flutter: #25     _drawFrame (dart:ui/hooks.dart:178:3)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired:
flutter:   RenderConstrainedBox#ecc56 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT
flutter:   creator: SizedBox.expand ← UiKitView ← WebView ← Stack ← RecaptchaV2 ← Center ← Column ← Container
flutter:   ← Column ← DecoratedBox ← ConstrainedBox ← Container ← ⋯
flutter:   parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=350.0, 0.0<=h<=Infinity)
flutter:   size: Size(350.0, Infinity)
flutter:   additionalConstraints: BoxConstraints(biggest)
flutter: This RenderObject has no descendants.
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: RenderStack object was given an infinite size during layout.

[VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding

**Comment by riclava** [comment]
Add this in your info.plist of iOS Runner
```
	<key>io.flutter.embedded_views_preview</key>
	<true/>
```

**Comment by BRLOKESH** [comment]
LOKESH:~ LOKESH$ touch /.bash_profile
LOKESH: LOKESH$ open -e /.bash_profile
LOKESH: LOKESH$ source $HOME/.bash_profile
LOKESH:~ LOKESH$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Users/apple/Desktop/flutter V1.5.4/flutter/bin:/Users/apple/Desktop/flutter V1.5.4/bin
LOKESH:~ LOKESH$

**Comment by denid88** [comment]
I have same problem in Android
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performResize():
RenderAndroidView object was given an infinite size during layout.

This probably means that it is a render object that tries to be as big as possible, but it was put inside another render object that allows its children to pick their own size.
The nearest ancestor providing an unbounded height constraint is: _RenderSingleChildViewport#8cc53 relayoutBoundary=up15 NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=381.4, 0.0<=h<=603.4)
...  layer: OffsetLayer#c65cd
...    offset: Offset(0.0, 0.0)
...  size: Size(381.4, 603.4)
The constraints that applied to the RenderAndroidView were: BoxConstraints(0.0<=w<=341.4, 0.0<=h<=Infinity)
The exact size it was given was: Size(341.4, Infinity)

See https://flutter.dev/docs/development/ui/layout/box-constraints for more information.

User-created ancestor of the error-causing widget was: 
  RecaptchaV2 file:///home/denid/Development/projects/customorrow/lib/src/screens/auth/registration_screen.dart:116:9
When the exception was thrown, this was the stack: 
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1953:9)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2021:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1738:7)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1740:6)
#4      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:154:5)
...
The following RenderObject was being processed when the exception was fired: RenderAndroidView#f1d5a NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=341.4, 0.0<=h<=Infinity)
...  semantic boundary
...  size: Size(341.4, Infinity)
RenderObject: RenderAndroidView#f1d5a NEEDS-LAYOUT NEEDS-PAINT
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=341.4, 0.0<=h<=Infinity)
  semantic boundary
  size: Size(341.4, Infinity)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by rendering library ═════════════════════════════════════════════════
RenderAndroidView object was given an infinite size during layout.
User-created ancestor of the error-causing widget was: 
  RecaptchaV2 file:///home/denid/Development/projects/customorrow/lib/src/screens/auth/registration_screen.dart:116:9
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by rendering library ═════════════════════════════════════════════════
RenderPointerListener object was given an infinite size during layout.
User-created ancestor of the error-causing widget was: 
  RecaptchaV2 file:///home/denid/Development/projects/customorrow/lib/src/screens/auth/registration_screen.dart:116:9
The following RenderObject was being processed when the exception was fired: RenderPointerListener#0676f relayoutBoundary=up23 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=341.4, 0.0<=h<=Infinity)
  size: Size(341.4, Infinity)
  behavior: deferToChild
  listeners: down
  child: RenderAndroidView#f1d5a NEEDS-PAINT
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(0.0<=w<=341.4, 0.0<=h<=Infinity)
    semantic boundary
    size: Size(341.4, Infinity)
RenderObject: RenderPointerListener#0676f relayoutBoundary=up23 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=341.4, 0.0<=h<=Infinity)
  size: Size(341.4, Infinity)
  behavior: deferToChild
  listeners: down
  child: RenderAndroidView#f1d5a NEEDS-PAINT
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(0.0<=w<=341.4, 0.0<=h<=Infinity)
    semantic boundary
    size: Size(341.4, Infinity)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by rendering library ═════════════════════════════════════════════════
RenderStack object was given an infinite size during layout.
User-created ancestor of the error-causing widget was: 
  RecaptchaV2 file:///home/denid/Development/projects/customorrow/lib/src/screens/auth/registration_screen.dart:116:9
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (5) Exception caught by rendering library ═════════════════════════════════════════════════
RenderFlex object was given an infinite size during layout.
User-created ancestor of the error-causing widget was: 
  Container file:///home/denid/Development/projects/customorrow/lib/src/screens/auth/registration_screen.dart:78:29
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (6) Exception caught by rendering library ═════════════════════════════════════════════════
RenderPadding object was given an infinite size during layout.
User-created ancestor of the error-causing widget was: 
  Container file:///home/denid/Development/projects/customorrow/lib/src/screens/auth/registration_screen.dart:78:29
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (7) Exception caught by rendering library ═════════════════════════════════════════════════
RenderDecoratedBox object was given an infinite size during layout.
User-created ancestor of the error-causing widget was: 
  Container file:///home/denid/Development/projects/customorrow/lib/src/screens/auth/registration_screen.dart:78:29
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (8) Exception caught by rendering library ═════════════════════════════════════════════════
RenderFlex object was given an infinite size during layout.
User-created ancestor of the error-causing widget was: 
  Container file:///home/denid/Development/projects/customorrow/lib/src/screens/auth/registration_screen.dart:72:23
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (9) Exception caught by rendering library ═════════════════════════════════════════════════
RenderFlex object was given an infinite size during layout.
User-created ancestor of the error-causing widget was: 
  ConstrainedBox file:///home/denid/Development/projects/customorrow/lib/src/screens/auth/registration_screen.dart:64:24
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (10) Exception caught by rendering library ════════════════════════════════════════════════
RenderConstrainedBox object was given an infinite size during layout.
User-created ancestor of the error-causing widget was: 
  SingleChildScrollView file:///home/denid/Development/projects/customorrow/lib/src/screens/auth/registration_screen.dart:63:22
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by mrgoonie** [comment]
Sorry for making you disapointed but I no longer maintain this plugin, it's using a very old version of Flutter, you have to find another one.

**Comment by nerypy** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @Rabid-Squirrel, @frkyldrm, @loicnestler, @vzts, @fahimaltinordu, @houpengxu, @s7v7nislands
